name: Spring Boot CI/CD Pipeline


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven



      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Flyway Migration
        run: mvn -B flyway:migrate -Dflyway.url=jdbc:mysql://mysql:3306/mydatabase -Dflyway.user=myuser -Dflyway.password=secret

      - name: Build with Maven
        run: mvn -B package --no-transfer-progress

      - name: Test with Maven
        run: mvn -B test --no-transfer-progress
