name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Define service containers for the job
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: verysecret
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: myuser
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        # Set health checks to wait until mysql is ready before starting the job
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --no-transfer-progress

      - name: Test with Maven
        run: mvn -B test --no-transfer-progress

